### ISSUE TITLE
What's the point?

### ISSUE THREAD

**Issue by jdoklovic** [malnick/mantle#1]
This seems to only be for protecting secrets from other developers on the same project.
e.g. sally has a db password and bill has a db password and they can edit the same marathon.json without exposing their passwords to each other.

If this is indeed the case, then this isn't really all that helpful. While we do have user specific secrets, we also have organizational secrets that are shared. Also, this whole thing seems to be negated by the fact that when you deploy to marathon, you're deploying a decrypted version of the json file and from there, anyone with access to the marathon UI can easily look at the config that was deployed and get the secrets in plain text.

Am I missing something?

Seems it would be much better to put the keys on the actual marathon instances so you could post the encrypted json and whenever marathon launched a new task instance it would decrypt the values and pass them to the executor. This way the Marathon UI wouldn't expose the secrets in plain text.

**Comment by mikljohansson** [comment]
@jdoklovic might want to have a look at [Secretary](https://github.com/meltwater/secretary) which we developed to solve the problems you described in pretty much the way you describe :-)

And perhaps also [Lighter](https://github.com/meltwater/secretary) for deploying stuff to Marathon which has integration with Secretary. Lighter helps manage the hopefully small config differences when the same app release goes through multiple envs and perhaps even serving as the deployment step in a CD pipeline (what we use it for). Enabling devteams to perform deployments to multiple Mesos/Marathon clusters without needing to give direct write access to the Marathon API or UI

And of course ideas for further improvements on Secretary/Lighter (or pull reqs) are most welcome

**Comment by malnick** [comment]
I wrote this so we could store the JSON on git while allowing multi user support. Sure, you can hid passwords from each Dev but the main point is to allow devs to encrypt but disallow, if desired, them from decrypting (deploy to marathon).

It's a site specific use case, not intended to suit all user cases.

**Comment by malnick** [comment]
I wrote this so we could store the JSON on git while allowing multi user support. Sure, you can hide passwords from each dev but the main point is to allow devs to encrypt but disallow, if desired, them from decrypting (deploy to marathon).

It's a site specific use case, not intended to suit all user cases. This project has a lot of holes (I wrote it for a previous job). Mainly, there is no SSL support, the JSON is posted over clear text (at the time I wrote this, Marathon didn't have SSL).

I haven't used this project since leaving that job but I still use it as one possible method to deal with secret storage. I'd be the first to admit it's far from perfect.
